### ISSUE TITLE
Use system python packages

### ISSUE THREAD

**Issue by danielkucera** [Hy3n4/ha-cc-cometblue#3]
You don't need to copy system libraries iniside venv. You can either create venv with switch `--system-site-packages` or if you already have venv created just delete `your_venv_dir/lib/pythonXXX/no-global-site-packages.txt`

I'm referring to this:
https://github.com/Hy3n4/ha-cc-cometblue/blame/master/README.md#L59

**Comment by danielkucera** [comment]
BTW thanks for this repo and guide!

**Comment by Hy3n4** [comment]
Thanks. You are right that would be much easier.
Did you test that it really works as desired? I don't have much time for testing these days.

**Comment by danielkucera** [comment]
Yes, I proceeded according to your guide, I just skipped the copying and enabled system site-packages and it works nicely.
